---
title: "Outline Analysis"
author: "Alex Gregory"
date: "2022-11-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(Momocs)
library(tidyr)
library(dplyr)
library(tidyverse)
library(stringr)
library(DescTools)
library(dispRity)
```

```{r}
BPA_files <- list.files(paste0(here::here(),"/data/BPA/Silhouettes"), pattern = 'plan', full.names = TRUE)

KG_files <- list.files(paste0(here::here(),"/data/KG/Silhouettes"), pattern="plan",
                     full.names=T)

NBC_files <- list.files(paste0(here::here(),"/data/NBC/Silhouettes"), pattern="plan",, 
                     full.names=T)

BNK1_files <- list.files(paste0(here::here(),"/data/BNK1/Silhouettes"), pattern="plan",
                     full.names=T)

MAT_files <- list.files(paste0(here::here(),"/data/MAT/Silhouettes"), pattern="plan",
                     full.names=T)


BPA <- Momocs::import_jpg(BPA_files)
KG <- Momocs::import_jpg(KG_files)
NBC <- Momocs::import_jpg(NBC_files)
BNK1 <- Momocs::import_jpg(BNK1_files)
MAT <- Momocs::import_jpg(MAT_files)

```

```{r}
li <- list()
li <- append(BPA, KG)
li <- append(li, NBC)
li <- append(li, BNK1)
li <- append(li, MAT)

coo <- Momocs::Out(li, fac=c(rep("BPA", length(BPA)),
                             rep("KG", length(KG)),
                             rep("NBC", length(NBC)),
                             rep("BNK1", length(BNK1)),
                             rep("MAT", length(MAT)))
                   )

#Momocs::panel(coo, fac = "value")
```

```{r}
coo_std <- coo |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()

coo.f <- Momocs::efourier(coo_std)


coo.p <- Momocs::PCA(coo.f)
coo.p$fac$value = factor(coo.p$fac$value)
```

```{r}
plot_PCA(coo.p, ~value)
Momocs::MANOVA(coo.p, ~value)
MANOVA_PW(coo.p, fac = "value", retain = 3)

lda <- LDA(coo.p, 1)
plot_LDA(lda)
```

```{r}

grouped_data <- custom.subsets(coo.p$x[,1:3], group = as.factor(coo.p$fac$value))

bootstrapped_data <- boot.matrix(grouped_data, bootstraps = 1000)

disparity_results <- dispRity(bootstrapped_data, metric = c(sum, variances))

disparity_var <- dispRity(bootstrapped_data, metric = variances)

summary(disparity_results)

test.dispRity(disparity_results, bhatt.coeff,
  correction = "bonferroni")

test.dispRity(disparity_results, test = t.test, comparisons = "pairwise",
              correction = "bonferroni")


test.dispRity(disparity_var, test = t.test, comparisons = "pairwise",
     concatenate = FALSE, correction = "bonferroni",
     conc.quantiles = c(mean, c(95, 5)))


plot(disparity_results, type = "box", ylab = "Sum of Variance")
plot(disparity_var, type = "box")
```

# Examine BNK1 separately by Strata

```{r}

BNK1_1 <- BNK1_files[BNK1_files %like% "%_1_%"]
BNK1_2 <- BNK1_files[BNK1_files %like% "%_2_%"]
BNK1_4 <- BNK1_files[BNK1_files %like% "%_4_%"]
BNK1_5 <- BNK1_files[BNK1_files %like% "%_5_%"]
BNK1_6 <- BNK1_files[BNK1_files %like% "%_6_%"]
BNK1_7 <- BNK1_files[BNK1_files %like% "%_7_%"]
BNK1_8 <- BNK1_files[BNK1_files %like% "%_8_%"]
BNK1_9 <- BNK1_files[BNK1_files %like% "%_9_%"]
BNK1_10 <- BNK1_files[BNK1_files %like% "%_10_%"]

BNK1_2.5 <- append(BNK1_2, c(BNK1_4, BNK1_5))
BNK1_6.7 <- append(BNK1_6, BNK1_7)


two_five <- Momocs::import_jpg(BNK1_2.5)
six_seven <- Momocs::import_jpg(BNK1_6.7)


######################################
one <- Momocs::import_jpg(BNK1_1)
two <- Momocs::import_jpg(BNK1_2)
four <- Momocs::import_jpg(BNK1_4)
five <- Momocs::import_jpg(BNK1_5)
six <- Momocs::import_jpg(BNK1_6)
seven <- Momocs::import_jpg(BNK1_7)
eight <- Momocs::import_jpg(BNK1_8)
nine <- Momocs::import_jpg(BNK1_9)
ten <- Momocs::import_jpg(BNK1_10)
```


```{r}
bnk1_all = c(one, two, four, five, six, seven, eight, nine, ten)

coo_bnk_all = Momocs::Out(bnk1_all,
                          fac = c(
                            rep("one", length(one)),
                            rep("two", length(two)),
                            rep("four", length(four)),
                            rep("five", length(five)),
                            rep("six", length(six)),
                            rep("seven", length(seven)),
                            rep("eight", length(eight)),
                            rep("nine", length(nine)),
                            rep("ten", length(ten))
                          ))

#Momocs::panel(coo_bnk_all, fac = "value")
```

```{r}
coo_bnk_all_std <- coo_bnk_all |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()


coo.f_bnk_all <- Momocs::efourier(coo_bnk_all_std)
coo.p_bnk_all <- Momocs::PCA(coo.f_bnk_all)

coo.p_bnk_all$fac$value = factor(coo.p_bnk_all$fac$value,
                                 levels = c("one", "two", "four", "five", "six",
                                                 "seven", "eight", "nine", "ten"))
```

```{r}
plot_PCA(coo.p_bnk_all, ~value)
Momocs::MANOVA(coo.p_bnk_all, ~value)
MANOVA_PW(coo.p_bnk_all, fac = "value", retain = 3)

lda_bnk_all <- LDA(coo.p_bnk_all, 1)
plot_LDA(lda_bnk_all)
```

```{r}
grouped_data_bnk <- custom.subsets(coo.p_bnk_all$x[,1:3], 
                                   group = as.factor(coo.p_bnk_all$fac$value))

bootstrapped_data_bnk <- boot.matrix(grouped_data_bnk, bootstraps = 1000)

disparity_results_bnk <- dispRity(bootstrapped_data_bnk, 
                                  metric = c(sum, variances))

disparity_var_bnk <- dispRity(bootstrapped_data_bnk, metric = variances)

summary(disparity_results_bnk)
test.dispRity(disparity_results_bnk, bhatt.coeff,
  correction = "bonferroni")

test.dispRity(disparity_results_bnk, test = wilcox.test,
              comparisons = "pairwise",
     correction = "bonferroni")



test.dispRity(disparity_var_bnk, test = t.test, comparisons = "pairwise",
     concatenate = FALSE, correction = "bonferroni",
     conc.quantiles = c(mean, c(95, 5)))

plot(disparity_results_bnk, type = "box", ylab = "Sum of Variance")
plot(disparity_var_bnk, type = "box")
```







```{r}
li_bnk <- list()
li_bnk <- append(one, two_five)

li_bnk <- append(li_bnk, six_seven)

coo_bnk <- Momocs::Out(li_bnk, fac=c(rep("one", length(one)),
                             rep("two-five", length(two_five)),
                             rep("six-seven", length(six_seven))))

#Momocs::panel(coo_bnk, fac = "value")
```


```{r}
coo_bnk_std <- coo_bnk |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()


coo.f_bnk <- Momocs::efourier(coo_bnk_std)
coo.p_bnk <- Momocs::PCA(coo.f_bnk)

coo.p_bnk$fac$value = factor(coo.p_bnk$fac$value)
```

```{r}
plot_PCA(coo.p_bnk, ~value)
Momocs::MANOVA(coo.p_bnk, ~value)
MANOVA_PW(coo.p_bnk, fac = "value", retain = 3)

lda_bnk <- LDA(coo.p_bnk, 1)
plot_LDA(lda_bnk)
```


```{r}
grouped_data_bnk <- custom.subsets(coo.p_bnk$x[,1:3], 
                                   group = as.factor(coo.p_bnk$fac$value))

bootstrapped_data_bnk <- boot.matrix(grouped_data_bnk, bootstraps = 1000)

disparity_results_bnk <- dispRity(bootstrapped_data_bnk, 
                                  metric = c(sum, variances))

disparity_var_bnk <- dispRity(bootstrapped_data_bnk, metric = variances)

summary(disparity_results_bnk)
test.dispRity(disparity_results_bnk, bhatt.coeff,
  correction = "bonferroni")

test.dispRity(disparity_results_bnk, test = wilcox.test,
              comparisons = "pairwise",
     correction = "bonferroni")
plot(disparity_results_bnk, type = "box")


test.dispRity(disparity_var_bnk, test = t.test, comparisons = "pairwise",
     concatenate = FALSE, correction = "bonferroni",
     conc.quantiles = c(mean, c(95, 5)))

plot(disparity_var_bnk, type = "box")
```

# Examine NBC separately by Strata

```{r}
#NBC_1 <- NBC.lf[NBC.lf %like% "%_1_%"]
NBC_3 <- NBC_files[NBC_files %like% "%_3_%"]
NBC_4 <- NBC_files[NBC_files %like% "%_4_%"]
NBC_5 <- NBC_files[NBC_files %like% "%_5_%"]
NBC_8 <- NBC_files[NBC_files %like% "%_8_%"]


NBC_4.8 <- append(NBC_4, c(NBC_5, NBC_8))
NBCfour_eight <- Momocs::import_jpg(NBC_4.8)


#NBCone <- Momocs::import_jpg(NBC_1)
NBCthree <- Momocs::import_jpg(NBC_3)
NBCfour <- Momocs::import_jpg(NBC_4)
NBCfive <- Momocs::import_jpg(NBC_5)
NBCeight <- Momocs::import_jpg(NBC_8)


```


```{r}
nbc_all = c(#NBCone, 
            NBCthree, 
            NBCfour, 
            NBCfive, 
            NBCeight)

coo_nbc_all = Momocs::Out(nbc_all,
                          fac = c(
                            #rep("one", length(NBCone)),
                            rep("three", length(NBCthree)),
                            rep("four", length(NBCfour)),
                            rep("five", length(NBCfive)),
                            rep("eight", length(NBCeight))
                          ))

#Momocs::panel(coo_bnk_all, fac = "value")
```

```{r}
coo_nbc_all_std <- coo_nbc_all |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()


coo.f_nbc_all <- Momocs::efourier(coo_nbc_all_std)
coo.p_nbc_all <- Momocs::PCA(coo.f_nbc_all)

coo.p_nbc_all$fac$value = factor(coo.p_nbc_all$fac$value,
                                 levels = c(#"one", 
                                            "three", 
                                            "four", 
                                            "five",
                                            "eight"))
```

```{r}
plot_PCA(coo.p_nbc_all, ~value)
Momocs::MANOVA(coo.p_nbc_all, ~value)
MANOVA_PW(coo.p_nbc_all, fac = "value", retain = 3)

lda_nbc_all <- LDA(coo.p_nbc_all, 1)
plot_LDA(lda_nbc_all)
```

```{r}
grouped_data_nbc <- custom.subsets(coo.p_nbc_all$x[,1:3], 
                                   group = as.factor(coo.p_nbc_all$fac$value))

bootstrapped_data_nbc <- boot.matrix(grouped_data_nbc, bootstraps = 1000)

disparity_results_nbc <- dispRity(bootstrapped_data_nbc, 
                                  metric = c(sum, variances))

disparity_var_nbc <- dispRity(bootstrapped_data_nbc, metric = variances)

summary(disparity_results_nbc)
test.dispRity(disparity_results_nbc, bhatt.coeff,
  correction = "bonferroni")

test.dispRity(disparity_results_nbc, test = wilcox.test,
              comparisons = "pairwise",
     correction = "bonferroni")



test.dispRity(disparity_var_nbc, test = t.test, comparisons = "pairwise",
     concatenate = FALSE, correction = "bonferroni",
     conc.quantiles = c(mean, c(95, 5)))

plot(disparity_results_nbc, type = "box", ylab = "Sum of Variance")
plot(disparity_var_nbc, type = "box")
```




```{r}
li_nbc <- list()
li_nbc <- append(NBCthree, NBCfour_eight)

coo_nbc <- Momocs::Out(li_nbc, fac=c(rep("three", length(NBCthree)),
                             rep("four-eight",length(NBCfour_eight))))

#Momocs::panel(coo_nbc, fac = "value")
```


```{r}
coo_nbc_std <- coo_nbc |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()


coo.f_nbc <- Momocs::efourier(coo_nbc_std)
coo.p_nbc <- Momocs::PCA(coo.f_nbc)

coo.p_nbc$fac$value = factor(coo.p_nbc$fac$value)
```

```{r}
plot_PCA(coo.p_nbc, ~value)
Momocs::MANOVA(coo.p_nbc, ~value)
MANOVA_PW(coo.p_nbc, fac = "value", retain = 3)

lda_nbc <- LDA(coo.p_nbc, 1)
plot_LDA(lda_nbc)
```

```{r}
grouped_data_nbc <- custom.subsets(coo.p_nbc$x[,1:3], group = as.factor(coo.p_nbc$fac$value))

bootstrapped_data_nbc <- boot.matrix(grouped_data_nbc, bootstraps = 1000)

disparity_results_nbc <- dispRity(bootstrapped_data_nbc, metric = c(sum, variances))


disparity_var_nbc <- dispRity(bootstrapped_data_nbc, metric = variances)

summary(disparity_results_nbc)
test.dispRity(disparity_results_nbc, bhatt.coeff,
  correction = "bonferroni")

test.dispRity(disparity_results_nbc, test = wilcox.test)
plot(disparity_results_nbc, type = "box")


test.dispRity(disparity_var_nbc, test = t.test,
     concatenate = FALSE,
     conc.quantiles = c(mean, c(95, 5)))

plot(disparity_var_nbc, type = "box")
```

# Examine KG separately by Strata

```{r}

DGL <- KG_files[KG_files %like% "%_DGL_%"]
GBL <- KG_files[KG_files %like% "%_GBL_%"]
SGL <- KG_files[KG_files %like% "%_SGL_%"]

DGL <- Momocs::import_jpg(DGL)
GBL <- Momocs::import_jpg(GBL)
SGL <- Momocs::import_jpg(SGL)

```

```{r}
li_kg <- list()
li_kg <- append(DGL, GBL)

li_kg <- append(li_kg, SGL)

coo_kg <- Momocs::Out(li_kg, fac=c(rep("DGL", length(DGL)),
                             rep("GBL", length(GBL)),
                             rep("SGL", length(SGL))))

#Momocs::panel(coo_kg, fac = "value")
```

```{r}
coo_kg_std <- coo_kg |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()


coo.f_kg <- Momocs::efourier(coo_kg_std)
coo.p_kg <- Momocs::PCA(coo.f_kg)

coo.p_kg$fac$value = factor(coo.p_kg$fac$value)
```

```{r}
plot_PCA(coo.p_kg, ~value)
Momocs::MANOVA(coo.p_kg, ~value)
MANOVA_PW(coo.p_kg, fac = "value", retain = 3)

lda_kg <- LDA(coo.p_kg, 1)
plot_LDA(lda_kg)
```

```{r}
grouped_data_kg <- custom.subsets(coo.p_kg$x[,1:3], 
                                  group = as.factor(coo.p_kg$fac$value))

bootstrapped_data_kg <- boot.matrix(grouped_data_kg, bootstraps = 1000)

disparity_results_kg<- dispRity(bootstrapped_data_kg, metric = c(sum, variances))


disparity_var_kg <- dispRity(bootstrapped_data_kg, metric = variances)

summary(disparity_results_kg)
test.dispRity(disparity_results_kg, bhatt.coeff,
  correction = "bonferroni")

test.dispRity(disparity_results_kg, test = wilcox.test,
  correction = "bonferroni")



test.dispRity(disparity_var_kg, test = t.test,
     concatenate = FALSE,
  correction = "bonferroni",
     conc.quantiles = c(mean, c(95, 5)))

plot(disparity_results_kg, type = "box", ylab = "Sum of Variance")
plot(disparity_var_kg, type = "box")
```

# Examine MAT separately by Strata

```{r}

C <- MAT_files[MAT_files %like% "%plan%"]

C <- Momocs::import_jpg(C)

```

```{r}
li_mat <- list()
li_mat <- append(C, li_mat)

coo_mat <- Momocs::Out(li_mat, fac=c(rep("C", length(C))))

#Momocs::panel(coo_mat, fac = "value")
```

```{r}
coo_mat_std <- coo_mat |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()


coo.f_mat <- Momocs::efourier(coo_mat_std)
coo.p_mat <- Momocs::PCA(coo.f_mat)

coo.p_mat$fac$value = factor(coo.p_mat$fac$value)
```

```{r}
plot_PCA(coo.p_mat, ~value)
```

```{r}
grouped_data_mat <- custom.subsets(coo.p_mat$x[,1:3], 
                                  group = as.factor(coo.p_mat$fac$value))

bootstrapped_data_mat <- boot.matrix(grouped_data_mat, bootstraps = 1000)

disparity_results_mat<- dispRity(bootstrapped_data_mat, metric = c(sum, variances))


disparity_var_mat <- dispRity(bootstrapped_data_mat, metric = variances)


plot(disparity_results_mat, type = "box", ylab = "Sum of Variance", xlab = "")
plot(disparity_var_mat, type = "box")
```



# Examine BPA separately by Strata

```{r}

BLD <- BPA_files[BPA_files %like% "%plan%"]

BLD <- Momocs::import_jpg(BLD)

```

```{r}
li_bpa <- list()
li_bpa <- append(BLD, li_bpa)

coo_bpa <- Momocs::Out(li_bpa, fac=c(rep("BLD", length(BLD))))

#Momocs::panel(coo_bpa, fac = "value")

```

```{r}
coo_bpa_std <- coo_bpa |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()


coo.f_bpa <- Momocs::efourier(coo_bpa_std)
coo.p_bpa <- Momocs::PCA(coo.f_bpa)

coo.p_bpa$fac$value = factor(coo.p_bpa$fac$value)
```

```{r}
plot_PCA(coo.p_bpa, ~value)
```

```{r}
grouped_data_bpa <- custom.subsets(coo.p_bpa$x[,1:3], 
                                  group = as.factor(coo.p_bpa$fac$value))

bootstrapped_data_bpa <- boot.matrix(grouped_data_bpa, bootstraps = 1000)

disparity_results_bpa <- dispRity(bootstrapped_data_bpa, metric = c(sum, variances))


disparity_var_bpa <- dispRity(bootstrapped_data_bpa, metric = variances)


plot(disparity_results_bpa, type = "box", ylab = "Sum of Variance", xlab = "")
plot(disparity_var_bpa, type = "box")
```

# Within and Between Sites

```{r}
li_all_1 <- list()
li_all_1 <- append(C, li_kg)
li_all_1 <- append(li_all_1, six_seven)

coo_all_1 <- Momocs::Out(li_all_1, fac=c(rep("MAT (5.4-7.7ka)", length(C)),
                                     rep("KG (6.6ka)", length(DGL)+
                                           length(GBL) + 
                                           length(SGL)),
                                     rep("BNK1 (6.7ka)", length(six_seven))))

Momocs::panel(coo_all_1, fac = "value")


li_all_2 <- list()
li_all_2 <- append(NBCthree, NBCfour_eight)
li_all_2 <- append(li_all_2, two_five)

coo_all_2 <- Momocs::Out(li_all_2, fac=c(rep("NBC (3ka)", length(NBCthree)),
                                         rep("NBC (4.8ka)", 
                                             length(NBCfour_eight)),
                                     rep("BNK1 (2.5ka)", length(two_five))))

Momocs::panel(coo_all_2, fac = "value")



```

```{r}
coo_all1_std <- coo_all_1 |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()

coo_f_all1 <- Momocs::efourier(coo_all1_std)

coo_pca_all1 <- Momocs::PCA(coo_f_all1)
coo_pca_all1$fac$value = factor(coo_pca_all1$fac$value)


#######################################################
coo_all2_std <- coo_all_2 |>
  Momocs::coo_center() |> Momocs::coo_scale() |>
  Momocs::coo_align()

coo_f_all2 <- Momocs::efourier(coo_all2_std)

coo_pca_all2 <- Momocs::PCA(coo_f_all2)
coo_pca_all2$fac$value = factor(coo_pca_all2$fac$value)


```

```{r}
plot_PCA(coo_pca_all1, ~value)
Momocs::MANOVA(coo_pca_all1, ~value)
MANOVA_PW(coo_pca_all1, fac = "value", retain = 3)

all_lda1 <- LDA(coo_pca_all1, 1)
plot_LDA(all_lda1)

```

```{r}
plot_PCA(coo_pca_all2, ~value)
Momocs::MANOVA(coo_pca_all2, ~value)
MANOVA_PW(coo_pca_all2, fac = "value", retain = 3)

all_lda2 <- LDA(coo_pca_all2, 1)
plot_LDA(all_lda2)
```

```{r}
grouped_data_all1 <- custom.subsets(coo_pca_all1$x[,1:3], 
                                   group = as.factor(coo_pca_all1$fac$value))

bootstrapped_data_all1 <- boot.matrix(grouped_data_all1, bootstraps = 1000)

disparity_results_all1 <- dispRity(bootstrapped_data_all1, 
                                  metric = c(sum, variances))

disparity_var_all1 <- dispRity(bootstrapped_data_all1, metric = variances)

summary(disparity_results_all1)
test.dispRity(disparity_results_all1, bhatt.coeff,
  correction = "bonferroni")





test.dispRity(disparity_results_all1, test = wilcox.test,
              comparisons = "pairwise", correction = "bonferroni")

test.dispRity(disparity_var_all1, test = t.test, comparisons = "pairwise",
     concatenate = FALSE, correction = "bonferroni",
     conc.quantiles = c(mean, c(95, 5)))


plot(disparity_results_all1, type = "box")
plot(disparity_var_all1, type = "box")
```

```{r}
grouped_data_all2 <- custom.subsets(coo_pca_all2$x[,1:3], 
                                   group = as.factor(coo_pca_all2$fac$value))

bootstrapped_data_all2 <- boot.matrix(grouped_data_all2, bootstraps = 1000)

disparity_results_all2 <- dispRity(bootstrapped_data_all2, 
                                  metric = c(sum, variances))

disparity_var_all2 <- dispRity(bootstrapped_data_all2, metric = variances)

summary(disparity_results_all2)
test.dispRity(disparity_results_all2, bhatt.coeff,
  correction = "bonferroni")





test.dispRity(disparity_results_all2, test = wilcox.test,
              comparisons = "pairwise", correction = "bonferroni")

test.dispRity(disparity_var_all2, test = t.test, comparisons = "pairwise",
     concatenate = FALSE, correction = "bonferroni",
     conc.quantiles = c(mean, c(95, 5)))


plot(disparity_results_all2, type = "box")
plot(disparity_var_all2, type = "box")
```
